[package]
name = "text-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.9.6"
glib = "0.20.9"
vte4 = "0.8"
home = "0.5"
mime_guess = "2.0"
gdk-pixbuf = "0.18"
sourceview5 = "0.9.1"  # For syntax highlighting
once_cell = "1.21"  # For thread-safe lazy initialization